name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests
        run: ./Scripts/run_tests.sh

      - name: Build app
        run: ./Scripts/build_app.sh
